classes: {
  base: {
    style: {
      bold: true
      font-size: 28
    }
  }

  person: {
    shape: person
  }

  animated: {
    style: {
      animated: true
    }
  }

  multiple: {
    style: {
      multiple: true
    }
  }

  enqueue: {
    label: Enqueue Task
  }

  dispatch: {
    label: Dispatch Task
  }

  library: {
    style: {
      bold: true
      font-size: 32
      fill: PapayaWhip
      fill-pattern: grain
      border-radius: 8
      font: mono
    }
  }

  task: {
    style: {
      bold: true
      font-size: 32
    }
  }
}
