direction: right

classes: {
  user: {
    shape: person
    style: {
      multiple: true
      bold: true
      font-size: 28
    }
  }

  connect: {
    style: {
      bold: true
      font-size: 28
    }
  }

  animated: {
    style: {
      animated: true
    }
  }

  enqueue: {
    label: Enqueue Task
  }

  dispatch: {
    label: Dispatch Task
  }

  library: {
    style: {
      bold: true
      font-size: 32
      fill: PapayaWhip
      fill-pattern: grain
      border-radius: 8
      font: mono
    }
  }

  task: {
    style: {
      bold: true
      font-size: 32
    }
  }

  multiple: {
    style: {
      multiple: true
    }
  }
}

user01: {
  label: User01
  class: user
}

user02: {
  label: User02
  class: user
}

user03: {
  label: User03
  class: user
}

user01 -> container.task01: {
  label: Create Task
  class: [connect; animated]
}
user02 -> container.task02: {
  label: Create Task
  class: [connect; animated]
}
user03 -> container.task03:  {
  label: Create Task
  class: [connect; animated]
}

container: Application {
  direction: right
  style: {
    bold: true
    font-size: 28
  }
  icon: https://icons.terrastruct.com/dev%2Fgo.svg

  task01: {
    icon: https://icons.terrastruct.com/essentials%2F092-graph%20bar.svg
    class: [task; multiple]
  }

  task02: {
    icon: https://icons.terrastruct.com/essentials%2F095-download.svg
    class: [task; multiple]
  }

  task03: {
    icon: https://icons.terrastruct.com/essentials%2F195-attachment.svg
    class: [task; multiple]
  }

  queue: {
    label: Queue Library
    icon: https://icons.terrastruct.com/dev%2Fgo.svg
    style: {
      bold: true
      font-size: 32
      fill: honeydew
    }

    producer: {
      label: Producer
      class: library
    }

    consumer: {
      label: Consumer
      class: library
    }

    database: {
      label: Ring\nBuffer
      shape: cylinder
      style: {
        bold: true
        font-size: 32
        fill-pattern: lines
        font: mono
      }
    }

    producer -> database
    database -> consumer
  }

  worker01: {
    icon: https://icons.terrastruct.com/essentials%2F092-graph%20bar.svg
    class: [task]
  }

  worker02: {
    icon: https://icons.terrastruct.com/essentials%2F095-download.svg
    class: [task]
  }

  worker03: {
    icon: https://icons.terrastruct.com/essentials%2F092-graph%20bar.svg
    class: [task]
  }

  worker04: {
    icon: https://icons.terrastruct.com/essentials%2F195-attachment.svg
    class: [task]
  }

  task01 -> queue.producer: {
    class: [connect; enqueue]
  }
  task02 -> queue.producer: {
    class: [connect; enqueue]
  }
  task03 -> queue.producer: {
    class: [connect; enqueue]
  }
  queue.consumer -> worker01: {
    class: [connect; dispatch]
  }
  queue.consumer -> worker02: {
    class: [connect; dispatch]
  }
  queue.consumer -> worker03: {
    class: [connect; dispatch]
  }
  queue.consumer -> worker04: {
    class: [connect; dispatch]
  }
}
